# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lnZHTtB9UE57pXdpSJEuXcUC1fb9sZXV
"""

"""
Lab 6 Starter Code
K-Means From Scratch

This code provides a skeleton for implementing K-Means clustering.
Students are expected to complete the TODO sections.
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris, make_blobs

# ============================================================
# DATASET LOADERS
# ============================================================


def load_iris_dataset():
    """
    Load the Iris dataset.

    Tasks:
    - Select only two features: Sepal Length and Petal Length
      as specified in the lab (for 2D visualization).
    - Return the data as a NumPy array X of shape (150, 2).
    """
    data = load_iris()

    # TODO: select two features
    # Indices for Sepal Length (0) and Petal Length (2)
    X = data.data[:, [0, 2]]

    return X


def generate_blobs(separable=True):
    """
    Generate synthetic clusters using sklearn.make_blobs.

    Parameters:
    - separable: if True, generate well-separated clusters
                 if False, generate overlapping clusters

    Tasks:
    - Create a dataset X with multiple clusters.
    - This allows observing K-Means behavior on different
      cluster distributions.
    """
    if separable:
        # TODO: generate well-separated blobs
        X, _ = make_blobs(n_samples=300, centers=3, cluster_std=0.60, random_state=42)
    else:
        # TODO: generate overlapping blobs
        X, _ = make_blobs(n_samples=300, centers=3, cluster_std=2.0, random_state=42)

    return X


# ============================================================
# HELPER FUNCTIONS
# ============================================================


def centroid_shift(old_centroids, new_centroids):
    """
    Compute how much centroids moved after an update.

    Parameters:
    - old_centroids: previous centroids
    - new_centroids: updated centroids

    Tasks:
    - Compute L2 norm of the difference between old and new centroids.
    - Used as a convergence criterion in K-Means.
    """
    # TODO implement actual computation
    # Example: np.linalg.norm(old_centroids - new_centroids)
    return np.linalg.norm(old_centroids - new_centroids)


# ============================================================
# KMEANS CLASS
# ============================================================


class MyKMeans:
    """
    K-Means clustering class.

    Tasks:
    - Implement K-Means algorithm from scratch.
    - Experiment with different distance metrics: Euclidean, Manhattan, Cosine.
    - Implement cluster assignment, centroid update, and convergence check.
    """

    def __init__(
        self, k=3, metric="euclidean", max_iter=100, tol=1e-4, random_state=42
    ):
        """
        Initialize K-Means parameters.

        Parameters:
        - k: number of clusters
        - metric: distance metric to use
        - max_iter: maximum iterations before stopping
        """
        self.k = k
        self.metric = metric
        self.max_iter = max_iter
        self.tol = tol
        self.random_state = random_state
        self.centroids = None
        self.labels_ = None

    # --------------------------------------------------------
    # DISTANCE FUNCTION
    # --------------------------------------------------------

    def _distance(self, x1, x2):
        """
        Compute distance between two points.

        Tasks:
        - Implement three distance metrics:
          * Euclidean: circular clusters
          * Manhattan: diamond-shaped clusters
          * Cosine: measures angle between vectors
        - Hint for cosine: distance = 1 - (dot(x1,x2)/(||x1||*||x2||))
        """
        # TODO implement euclidean distance
        if self.metric == "euclidean":
            return np.sqrt(np.sum((x1 - x2) ** 2))

        # TODO implement manhattan distance
        elif self.metric == "manhattan":
            return np.sum(np.abs(x1 - x2))

        # TODO implement cosine distance
        elif self.metric == "cosine":
            norm_x1 = np.linalg.norm(x1)
            norm_x2 = np.linalg.norm(x2)
            if norm_x1 == 0 or norm_x2 == 0:
                return 1.0
            dot_product = np.dot(x1, x2)
            return 1 - (dot_product / (norm_x1 * norm_x2))

        else:
            raise ValueError("Unknown metric")

    # --------------------------------------------------------

    def initialize_centroids(self, X):
        """
        Randomly select K points from dataset as initial centroids.

        Tasks:
        - Pick k random indices from X
        - Assign these points as initial centroids
        """
        # TODO
        indices = np.random.choice(X.shape[0], self.k, replace=False)
        return X[indices]

    # --------------------------------------------------------

    def assign_clusters(self, X, centroids):
        """
        Assign each point to the nearest centroid.

        Tasks:
        - Compute distance from each point to every centroid
        - Assign label based on nearest centroid
        - Return array of cluster labels
        """
        # TODO
        labels = []
        for x in X:
            distances = [self._distance(x, c) for c in centroids]
            labels.append(np.argmin(distances))
        return np.array(labels)

    # --------------------------------------------------------

    def update_centroids(self, X, labels):
        """
        Update centroid positions based on cluster assignments.

        Tasks:
        - For each cluster, compute mean of points assigned to it
        - If a cluster has no points (empty), randomly reinitialize
          its centroid (safeguard)
        """
        centroids = []

        for i in range(self.k):
            # TODO: get points belonging to cluster i
            cluster_points = X[labels == i]

            if len(cluster_points) == 0:
                # SAFEGUARD: choose random point as centroid
                # TODO
                centroid = X[np.random.choice(X.shape[0])]
            else:
                # TODO: compute mean of cluster points
                centroid = cluster_points.mean(axis=0)

            centroids.append(centroid)

        return np.array(centroids)

    # --------------------------------------------------------

    def fit(self, X):
        """
        Fit the K-Means model to the data X.

        Algorithm:
        1. Initialize centroids
        2. Assign points to nearest centroid
        3. Update centroids
        4. Repeat until convergence (centroid movement < tol)
        or max iterations reached

        Tasks:
        - Implement K-Means training loop
        - Use centroid_shift to detect convergence
        """
        np.random.seed(self.random_state)
        centroids = self.initialize_centroids(X)

        for iteration in range(self.max_iter):
            labels = self.assign_clusters(X, centroids)
            new_centroids = self.update_centroids(X, labels)

            # TODO compute centroid movement
            shift = centroid_shift(centroids, new_centroids)

            if shift < self.tol:
                break

            centroids = new_centroids

        self.centroids = centroids
        self.labels_ = self.assign_clusters(X, centroids)

    # --------------------------------------------------------

    def predict(self, X):
        """
        Predict cluster labels for new data points.

        Tasks:
        - Compute distance from each point to centroids
        - Assign each point to nearest centroid
        """
        # TODO
        return self.assign_clusters(X, self.centroids)

    # --------------------------------------------------------
    # INERTIA
    # --------------------------------------------------------

    def compute_inertia(self, X, labels, centroids):
        """
        Compute Within-Cluster Sum of Squares (WCSS / Inertia).

        Tasks:
        - For each point, compute squared distance to its centroid
        - Sum all squared distances
        - Lower values indicate tighter clusters
        """
        # TODO
        total_inertia = 0
        for i in range(self.k):
            cluster_points = X[labels == i]
            if len(cluster_points) > 0:
                # Using squared Euclidean distance for inertia calculation
                total_inertia += np.sum((cluster_points - centroids[i]) ** 2)
        return total_inertia


# ============================================================
# VISUALIZATION
# ============================================================


def plot_clusters(X, labels, centroids, title):
    """
    Scatter plot of clusters.

    Tasks:
    - Color points based on cluster labels
    - Plot centroids as 'X' markers
    """
    plt.scatter(X[:, 0], X[:, 1], c=labels, cmap="viridis", alpha=0.6)

    if centroids is not None:
        plt.scatter(
            centroids[:, 0],
            centroids[:, 1],
            marker="X",
            s=200,
            c="red",
            label="Centroids",
        )

    plt.title(title)
    plt.legend()


def plot_decision_boundaries(model, X):
    """
    Visualize clustering regions (decision boundaries).

    Tasks:
    - Create a mesh grid over the feature space
    - Predict cluster label for each grid point
    - Plot colored decision regions
    - Useful for comparing distance metrics
    """
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.05), np.arange(y_min, y_max, 0.05))
    grid = np.c_[xx.ravel(), yy.ravel()]
    Z = model.predict(grid)
    Z = Z.reshape(xx.shape)
    plt.contourf(xx, yy, Z, alpha=0.3, cmap="viridis")
    plt.scatter(X[:, 0], X[:, 1], c=model.labels_, cmap="viridis", edgecolor="k")
    plt.scatter(
        model.centroids[:, 0], model.centroids[:, 1], marker="X", s=200, c="red"
    )
    plt.title(f"Decision Boundaries ({model.metric})")
    plt.show()


# ============================================================
# ELBOW METHOD
# ============================================================


def plot_elbow_curve(X, k_values):
    """
    Elbow method to determine optimal K.

    Tasks:
    - Train K-Means for multiple K values
    - Compute inertia for each K
    - Plot inertia vs K
    - Observe the 'elbow' to estimate optimal clusters
    """
    inertias = []

    for k in k_values:
        model = MyKMeans(k=k)
        model.fit(X)
        labels = model.predict(X)

        # TODO compute inertia
        inertia = model.compute_inertia(X, labels, model.centroids)
        inertias.append(inertia)

    # TODO: plot inertia vs k
    plt.figure()
    plt.plot(k_values, inertias, "bo-")
    plt.xlabel("Number of Clusters (K)")
    plt.ylabel("Inertia (WCSS)")
    plt.title("Elbow Method for Optimal K")
    plt.grid(True)
    plt.show()


# ============================================================
# MAIN DEMO
# ============================================================


def main():
    """
    Main demonstration.

    Tasks:
    - Load Iris dataset
    - Run K-Means with different metrics: Euclidean, Manhattan, Cosine
    - Visualize resulting clusters
    - Run Elbow method to determine optimal K
    """
    X = load_iris_dataset()
    metrics = ["euclidean", "manhattan", "cosine"]

    for metric in metrics:
        plt.figure()
        model = MyKMeans(k=3, metric=metric)
        model.fit(X)
        labels = model.predict(X)
        plot_clusters(X, labels, model.centroids, f"Metric: {metric}")

    plt.show()

    # Elbow Method
    plot_elbow_curve(X, range(1, 10))


if __name__ == "__main__":
    main()