# -*- coding: utf-8 -*-
"""BSSE23058_A_ML_LAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQKbbmcdjRuBjzKvWpZBq0n67fuGLugT
"""

import numpy as np
import time
import matplotlib.pyplot as plt

# ================================
# PART A — GRADIENT DESCENT
# ================================


def scalar_function(x):
    return x**2 + 5


def scalar_gradient(x):
    return 2 * x


def gradient_descent_scalar(x0, alpha, steps=20):
    x = x0
    history = []
    for _ in range(steps):
        x = x - alpha * scalar_gradient(x)
        history.append(x)
    return history


def surface_function(v):
    x, y = v
    return x**2 + 3 * y**2


def surface_gradient(v):
    x, y = v
    return np.array([2 * x, 6 * y])


def gradient_descent_vector(v0, alpha, steps=20):
    v = v0.copy()
    history = []
    for _ in range(steps):
        v = v - alpha * surface_gradient(v)
        history.append(v.copy())
    return np.array(history)


def plot_trajectory(history):
    history = np.array(history)
    plt.plot(history[:, 0], history[:, 1], marker="o")
    plt.xlabel("x")
    plt.ylabel("y")
    plt.title("Gradient Descent Trajectory")
    plt.show()


# ================================
# PART B — KNN
# ================================


def generate_dataset(n=100, seed=42):
    np.random.seed(seed)
    class0 = np.random.multivariate_normal([0, 0], np.eye(2), n // 2)
    class1 = np.random.multivariate_normal([2, 2], np.eye(2), n // 2)
    X = np.vstack([class0, class1])
    y = np.array([0] * (n // 2) + [1] * (n // 2))
    return X, y


def euclidean_distance_loop(x, y):
    total_sum = 0
    for i in range(len(x)):
        total_sum += (x[i] - y[i]) ** 2
    return total_sum**0.5


def euclidean_distance_vectorized(x, y):
    return np.sqrt(np.sum((x - y) ** 2))
    # 1. (X_train - x_test): NumPy 'stretches' the 1D x_test across all rows of 2D X_train.
    # 2. Squares the differences element-wise.
    # 3. np.sum: Sums the squared differences across the feature columns (horizontal).
    # 4. np.sqrt: Computes the square root to finalize the Euclidean distance for each poin


def knn_predict(x_test, X_train, y_train, k):
    distances = np.sqrt(np.sum((X_train - x_test) ** 2, axis=1))
    neighbor_indices = np.argpartition(distances, k)[:k]
    k_labels = y_train[neighbor_indices]
    counts = np.bincount(k_labels)
    return np.argmax(counts)


# ================================
# PERFORMANCE COMPARISON UTILITIES
# ================================


def time_function(func, *args, repeats=1000):
    start = time.time()
    for _ in range(repeats):
        func(*args)
    end = time.time()
    return end - start


def compare_distance_performance(dim=1000):
    x = np.random.rand(dim)
    y = np.random.rand(dim)

    loop_time = time_function(euclidean_distance_loop, x, y)
    vec_time = time_function(euclidean_distance_vectorized, x, y)

    print(f"Loop-based distance time: {loop_time:.6f}s")
    print(f"Vectorized distance time: {vec_time:.6f}s")
    print(f"Speedup: {loop_time / vec_time:.2f}x")


def compare_knn_performance(n_samples=5000, n_features=10):
    X, y = generate_dataset(n_samples)
    x_test = X[0]
    k = 5

    start = time.time()
    for i in range(len(X)):
        euclidean_distance_loop(x_test, X[i])
    loop_time = time.time() - start

    start = time.time()
    _ = np.linalg.norm(X - x_test, axis=1)
    vec_time = time.time() - start

    print(f"KNN distance computation (loop): {loop_time:.6f}s")
    print(f"KNN distance computation (vectorized): {vec_time:.6f}s")
    print(f"Speedup: {loop_time / vec_time:.2f}x")
