# -*- coding: utf-8 -*-
"""bsse23058_a_ml_lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wOGgKAWvPTrC4wkYTCfQGfUeqnWy91Ke
"""

import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# DATA GENERATION
# ============================================================

def generate_dataset(n=10, noise_std=0.1, seed=42):
    np.random.seed(seed)
    x = np.linspace(0, 1, n)
    y = np.sin(2 * np.pi * x) + np.random.normal(0, noise_std, size=n)
    return x.reshape(-1, 1), y.reshape(-1, 1)

# ============================================================
# TASK A1: FEATURE ENGINEERING
# ============================================================

def build_polynomial_features(x, degree):
    X_poly = np.ones((len(x), 1))
    for d in range(1, degree + 1):
        X_poly = np.hstack((X_poly, x**d))
    return X_poly

# ============================================================
# TASK A2: NORMAL EQUATION
# ============================================================

def normal_equation(X, y):
    return np.linalg.inv(X.T @ X) @ X.T @ y

# ============================================================
# TASK B1: RIDGE REGRESSION
# ============================================================

def ridge_regression(X, y, lambda_):
    n_features = X.shape[1]
    I = np.eye(n_features)
    I[0, 0] = 0
    w = np.linalg.inv(X.T @ X + lambda_ * I) @ X.T @ y
    return w

# ================================
# ANALYSIS UTILITIES
# ================================


def compute_condition_number(X):
    return np.linalg.cond(X.T @ X)


def plot_results(x_train, y_train, x_plot, y_plot, title="Model Fit"):
    plt.figure(figsize=(8, 5))
    plt.scatter(x_train, y_train, color='blue', label='Train Data')
    plt.plot(x_plot, y_plot, color='red', label='Model Prediction')
    plt.title(title)
    plt.xlabel("x")
    plt.ylabel("y")
    plt.ylim(-1.5, 1.5)
    plt.legend()
    plt.show()


# ================================
# UNIT TESTS
# ================================


def test_polynomial_shape():
    x, _ = generate_dataset()
    X = build_polynomial_features(x, 20)
    assert X.shape[1] == 21, "Feature matrix should include bias + 20 degrees"


def test_normal_equation_solution():
    x, y = generate_dataset()
    X = build_polynomial_features(x, 2)
    w = normal_equation(X, y)
    assert w.shape[0] == X.shape[1], "Weight dimension mismatch"


def test_ridge_reduces_norm():
    x, y = generate_dataset()
    X = build_polynomial_features(x, 20)
    w_no_reg = normal_equation(X, y)
    w_reg = ridge_regression(X, y, 1.0)
    assert np.linalg.norm(w_reg) < np.linalg.norm(
        w_no_reg
    ), "Ridge should reduce coefficient magnitude"


def run_all_tests():
    test_polynomial_shape()
    test_normal_equation_solution()
    test_ridge_reduces_norm()
    print("All tests passed.")


if __name__ == "__main__":
    run_all_tests()


    x_train, y_train = generate_dataset(n=10)
    x_plot = np.linspace(0, 1, 100).reshape(-1, 1)

    degree = 20
    X_train = build_polynomial_features(x_train, degree)
    X_plot = build_polynomial_features(x_plot, degree)

    w_normal = normal_equation(X_train, y_train)
    y_pred_normal = X_plot @ w_normal

    print("--- 4	Part A — The Overfitting Demo ---")

    print("--- TASK A1: Polynomial Feature Matrix  ---")
    x, y = generate_dataset(n=10)
    X = build_polynomial_features(x, 20)
    print(f"Matrix shape: {X.shape}")

    print("--- Task A2: Normal Equation Regression   ---")
    plot_results(x_train, y_train, x_plot, y_pred_normal, title="Overfitting (λ=0)")

    print("--- Task A3: Coefficient Explosion & Stability   ---")
    print(f"Weight Norm: {np.linalg.norm(w_normal):.2e}")
    print(f"Condition Number: {compute_condition_number(X_train):.2e}")


    print("\n--- 5	Part B — Ridge Regression ---")
    print("--- Task B2: Regularization Study    ---")

    lambdas = [0, 1e-4, 1e-2, 1e-1, 1]

    for lam in lambdas:
        w_ridge = ridge_regression(X_train, y_train, lam)
        n_feat = X_train.shape[1]
        I_mat = np.eye(n_feat); I_mat[0, 0] = 0
        cond_val = np.linalg.cond(X_train.T @ X_train + lam * I_mat)

        print(f"λ={lam:<6} | Norm: {np.linalg.norm(w_ridge):.2e} | Condition: {cond_val:.2e}")

        if lam in [1e-4, 1e-2, 1]:
            plot_results(x_train, y_train, x_plot, X_plot @ w_ridge, title=f"Ridge Fit (λ={lam})")