# -*- coding: utf-8 -*-
"""bsse23058_a_ml_lab5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJ6qS2Mo4YcMj3YgjXqSxZlqJ8OnWE-T
"""

"""
Lab 6 Starter Code
Decision Tree Split using Gini and Information Gain
"""

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split


# ============================================================
# DATASET
# ============================================================


def load_binary_iris():
    """
    Load iris dataset but keep only two classes.

    This simplifies the task to binary classification
    so that Gini impurity is easier to compute.

    Returns
    -------
    X_train, X_test, y_train, y_test
    """

    data = load_iris()

    X = data.data
    y = data.target

    mask = y < 2
    X = X[mask]
    y = y[mask]

    return train_test_split(X, y, test_size=0.2, random_state=42)


# ============================================================
# STUDENT TASKS
# ============================================================


def gini(y):
    if len(y) == 0:
        return 0
    p0 = np.mean(y == 0)
    p1 = np.mean(y == 1)

    return 1 - (p0**2 + p1**2)


def information_gain(parent, left, right):
    parent_impurity = gini(parent)
    n = len(parent)
    n_left, n_right = len(left), len(right)

    if n == 0:
        return 0
    weighted_child_impurity = (n_left / n) * gini(left) + (n_right / n) * gini(right)

    return parent_impurity - weighted_child_impurity


def find_best_split(X, y):
    best_gain = -1
    best_feature = None
    best_threshold = None

    n_features = X.shape[1]

    for feature_idx in range(n_features):
        values = X[:, feature_idx]
        thresholds = candidate_thresholds(values)

        for threshold in thresholds:
            _, _, y_left, y_right = split_dataset(X, y, feature_idx, threshold)
            gain = information_gain(y, y_left, y_right)
            if gain > best_gain:
                best_gain = gain
                best_feature = feature_idx
                best_threshold = threshold

    return best_feature, best_threshold, best_gain


# ============================================================
# HELPER FUNCTIONS
# ============================================================


def split_dataset(X, y, feature, threshold):
    """
    Split dataset into left and right partitions.

    All samples with feature value <= threshold
    go to the left node.

    Returns
    -------
    X_left, X_right, y_left, y_right
    """

    mask = X[:, feature] <= threshold

    return X[mask], X[~mask], y[mask], y[~mask]


def candidate_thresholds(values):
    """
    Compute candidate thresholds for a feature.

    Thresholds are chosen as midpoints between
    consecutive sorted unique values.

    This mirrors the approach used in most
    decision tree implementations.
    """

    values = np.sort(np.unique(values))

    return (values[:-1] + values[1:]) / 2


def add_high_cardinality_feature(X):
    """
    Add deterministic high-cardinality feature.

    Each sample receives a unique value derived
    from its index.

    This allows us to observe the bias of
    decision trees toward features with many
    unique values.
    """

    N = len(X)
    index_feature = (np.arange(N) / N).reshape(-1, 1)
    return np.hstack([X, index_feature])


# ============================================================
# EXPERIMENT
# ============================================================


def run_split_experiment(X, y):

    feature, threshold, gain = find_best_split(X, y)

    print("Best Feature:", feature)
    print("Threshold:", threshold)
    print("Information Gain:", gain)


# ============================================================
# MAIN
# ============================================================


def main():

    X_train, X_test, y_train, y_test = load_binary_iris()

    print("Original Dataset")

    run_split_experiment(X_train, y_train)

    print("\nWith High Cardinality Feature")

    X_aug = add_high_cardinality_feature(X_train)

    run_split_experiment(X_aug, y_train)


if __name__ == "__main__":
    main()