# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# lab9_starter.py

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score
from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTEENN

# ==========================================================
# DATASETS (PROVIDED - DO NOT MODIFY)
# ==========================================================


def load_dataset_60_40():
    np.random.seed(42)

    normal = np.random.multivariate_normal(
        mean=[50, 50], cov=[[200, 80], [80, 200]], size=600
    )

    fraud = np.random.multivariate_normal(
        mean=[55, 55], cov=[[200, 80], [80, 200]], size=400  # VERY close mean
    )

    X = np.vstack([normal, fraud])
    y = np.array([0] * 600 + [1] * 400)

    return X, y


def load_dataset_90_10():
    np.random.seed(42)

    normal = np.random.multivariate_normal(
        mean=[50, 50], cov=[[300, 120], [120, 300]], size=900
    )

    fraud = np.random.multivariate_normal(
        mean=[51, 51], cov=[[300, 120], [120, 300]], size=100
    )

    X = np.vstack([normal, fraud])
    y = np.array([0] * 900 + [1] * 100)

    return X, y


# ==========================================================
# CORE TASKS
# ==========================================================


def train_logistic(X, y):
    """
    Train logistic regression using cross-entropy loss.
    """
    model = LogisticRegression(random_state=42, max_iter=1000)
    model.fit(X, y)
    return model


def evaluate_model(model, X, y):
    """
    Return accuracy and F1-score.
    """
    y_pred = model.predict(X)

    accuracy = accuracy_score(y, y_pred)
    f1 = f1_score(y, y_pred)

    return accuracy, f1


def apply_smote(X, y):
    """
    Apply SMOTE.
    """
    smote = SMOTE(random_state=42)
    X_resampled, y_resampled = smote.fit_resample(X, y)
    return X_resampled, y_resampled


def apply_smoteenn(X, y):
    """
    Apply SMOTEENN.
    """
    smoteenn = SMOTEENN(random_state=42)
    X_resampled, y_resampled = smoteenn.fit_resample(X, y)
    return X_resampled, y_resampled


def train_weighted_logistic(X, y):
    """
    Train logistic regression with class weights.
    """
    model = LogisticRegression(
        class_weight={0: 1, 1: 9}, random_state=42, max_iter=1000
    )
    model.fit(X, y)
    return model


# ==========================================================
# EXECUTION SCRIPT
# ==========================================================
if __name__ == "__main__":
    X, y = load_dataset_90_10()
    print("--- Testing on 90:10 Dataset ---")

    standard_model = train_logistic(X, y)
    acc, f1 = evaluate_model(standard_model, X, y)
    print(f"Standard Model -> Accuracy: {acc:.4f}, F1-Score: {f1:.4f}")

    X_smote, y_smote = apply_smote(X, y)
    smote_model = train_logistic(X_smote, y_smote)
    acc_smote, f1_smote = evaluate_model(smote_model, X, y)
    print(f"SMOTE Model    -> Accuracy: {acc_smote:.4f}, F1-Score: {f1_smote:.4f}")

    X_sme, y_sme = apply_smoteenn(X, y)
    sme_model = train_logistic(X_sme, y_sme)
    acc_sme, f1_sme = evaluate_model(sme_model, X, y)
    print(f"SMOTEENN Model -> Accuracy: {acc_sme:.4f}, F1-Score: {f1_sme:.4f}")

    weighted_model = train_weighted_logistic(X, y)
    acc_w, f1_w = evaluate_model(weighted_model, X, y)
    print(f"Weighted Model -> Accuracy: {acc_w:.4f}, F1-Score: {f1_w:.4f}")